spring.application.name=imaging-service
server.port=4007

spring.datasource.url=jdbc:postgresql://localhost:5432/medical_images
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

secret.key=dqYCMmwi5RRi2q3q0b32EZ3mR37RgQEJFfi3egXDQNI=

app.s3.bucket=hospital-medical-images-sg
image.storage.path=/app/images
